// SPDX-License-Identifier: LGPL-3.0-or-later
// fsuipc_offsets/fsuipc_offset_table.h
//
// Generated by python/generate_fsuipc_production_tables.py
// Contains ONLY offsets with real X-Plane DataRef implementations.
//
#pragma once

#include "fsuipc_offsets/Autopilot.h"
#include "fsuipc_offsets/Cockpit.h"
#include "fsuipc_offsets/Controls.h"
#include "fsuipc_offsets/Engines.h"
#include "fsuipc_offsets/Environment.h"
#include "fsuipc_offsets/Fuel.h"
#include "fsuipc_offsets/Misc.h"
#include "fsuipc_offsets/Plane.h"
#include "fsuipc_offsets/Pos_Attitude.h"
#include "fsuipc_offsets/Radios.h"
#include "fsuipc_offsets/Simulation.h"
#include "fsuipc_offsets/Unknown.h"
#include "fsuipc_offsets/Weather.h"

template<typename BridgeType>
inline void register_fsuipc_offset_tables(BridgeType& offset_bridge) {
    // Autopilot.h
    offset_bridge.register_table(fsuipc_offset_table_autopilot());
    // Cockpit.h
    offset_bridge.register_table(fsuipc_offset_table_cockpit());
    // Controls.h
    offset_bridge.register_table(fsuipc_offset_table_controls());
    // Engines.h
    offset_bridge.register_table(fsuipc_offset_table_engines());
    // Environment.h
    offset_bridge.register_table(fsuipc_offset_table_environment());
    // Fuel.h
    offset_bridge.register_table(fsuipc_offset_table_fuel());
    // Misc.h
    offset_bridge.register_table(fsuipc_offset_table_misc());
    // Plane.h
    offset_bridge.register_table(fsuipc_offset_table_plane());
    // Pos_Attitude.h
    offset_bridge.register_table(fsuipc_offset_table_pos_attitude());
    // Radios.h
    offset_bridge.register_table(fsuipc_offset_table_radios());
    // Simulation.h
    offset_bridge.register_table(fsuipc_offset_table_simulation());
    // Unknown.h
    offset_bridge.register_table(fsuipc_offset_table_unknown());
    // Weather.h
    offset_bridge.register_table(fsuipc_offset_table_weather());
}
